// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ftiJzUmOqlHLgva8jjZRuf9sBAoYxSc',
    appId: '1:692766555111:web:f0c19448b202bf190cdb42',
    messagingSenderId: '692766555111',
    projectId: 'virtudine-53fc9',
    authDomain: 'virtudine-53fc9.firebaseapp.com',
    databaseURL: 'https://virtudine-53fc9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'virtudine-53fc9.appspot.com',
    measurementId: 'G-JXE13XFE6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiw0UyjgCSPeuNZGrFY5IFgi3TPRQspmc',
    appId: '1:692766555111:android:286922691ee64ffa0cdb42',
    messagingSenderId: '692766555111',
    projectId: 'virtudine-53fc9',
    databaseURL: 'https://virtudine-53fc9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'virtudine-53fc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA087768bmcKmSuyn-BsaUxzRX8O0V5iKI',
    appId: '1:692766555111:ios:c577fa8f3073d0360cdb42',
    messagingSenderId: '692766555111',
    projectId: 'virtudine-53fc9',
    databaseURL: 'https://virtudine-53fc9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'virtudine-53fc9.appspot.com',
    iosClientId: '692766555111-6t3qckdd1lgcdbtrff3nhdpl1uc89nqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.virtudine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA087768bmcKmSuyn-BsaUxzRX8O0V5iKI',
    appId: '1:692766555111:ios:0e2cd49a3115676a0cdb42',
    messagingSenderId: '692766555111',
    projectId: 'virtudine-53fc9',
    databaseURL: 'https://virtudine-53fc9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'virtudine-53fc9.appspot.com',
    iosClientId: '692766555111-t26e2to3iqq841rm0snb59jbrcf7b51e.apps.googleusercontent.com',
    iosBundleId: 'com.example.virtudine.RunnerTests',
  );
}
